# Generated by Django 2.2.11 on 2020-04-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virData_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entries',
            new_name='Entry',
        ),
    ]
